gui:
  nerdFontsVersion: 3
  theme:
   unstagedChangesColor:
     - "#c53b53"
   selectedLineBgColor:
     - "#2d3f76"
   searchingActiveBorderColor:
     - "#ff966c"
     - "bold"
   optionsTextColor:
     - "#82aaff"
   inactiveBorderColor:
     - "#589ed7"
   defaultFgColor:
     - "#c8d3f5"
   cherryPickedCommitFgColor:
     - "#82aaff"
   cherryPickedCommitBgColor:
     - "#c099ff"
   activeBorderColor:
     - "#ff966c"
     - "bold"
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
keybinding:
  universal:
    quit: "q"
customCommands:
- key: b
  command: tig blame -- {{.SelectedFile.Name}}
  context: files
  description: blame file at tree
  subprocess: yes
- key: b
  command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
  context: commitFiles
  description: blame file at revision
  subprocess: yes
- key: B
  command: tig blame -- {{.SelectedCommitFile.Name}}
  context: commitFiles
  description: blame file at tree
  subprocess: yes
- key: t
  command: tig show {{.SelectedSubCommit.Sha}}
  context: subCommits
  description: tig commit (`t` again to browse files at revision)
  subprocess: yes
- key: t
  command: tig show {{.SelectedLocalBranch.Name}}
  context: localBranches
  description: tig branch (`t` again to browse files at revision)
  subprocess: yes
- key: t
  command: tig show {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}
  context: remoteBranches
  description: tig branch (`t` again to browse files at revision)
  subprocess: yes
- key: t
  command: tig {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
  context: commitFiles
  description: tig file (history of commits affecting file)
  subprocess: yes
- key: t
  command: tig -- {{.SelectedFile.Name}}
  context: files
  description: tig file (history of commits affecting file)
  subprocess: yes
